name: Terraform Checks and Plan

on:
  # Trigger on any commit to your feature branch
  push:
    branches:
      - jaspreet1388-patch-1

  # Still trigger on PRs later
  pull_request:

  # Allow running manually from Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  static-checks:
    name: Static Terraform Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/tf-app

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Terraform Init (no backend)
        run: terraform init -backend=false
      - name: Terraform Format Check
        run: terraform fmt -recursive -check
      - name: Terraform Validate
        run: terraform validate
      - name: Install TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Run TFLint
        run: tflint
      - name: Install Checkov
        run: pip install checkov
      - name: Run Checkov
        run: checkov -d .

  plan:
    name: Terraform Plan (Remote Backend)
    runs-on: ubuntu-latest
    needs: static-checks
    defaults:
      run:
        working-directory: infra/tf-app

    steps:
      - uses: actions/checkout@v4
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_READONLY }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Terraform Init (remote backend)
        run: terraform init -input=false
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tf-app/tfplan
